### ISSUE TITLE
log of memory bandwidth should also support zero value

### ISSUE THREAD

**Issue by GeertenV** [gvsoc/gvsoc-core#44]
https://github.com/gvsoc/gvsoc-core/blob/6ed2b5e31866b45297fd719bb0cef0126242a539/models/memory/memory.cpp#L231C8-L231C36

I propose the following change:
As the bandwidth is expressed as the 2log(bytes) in the python files a value of 0 would match a bandwidth of 1 byte per cycle.
Since this is a feasible bandwidth I'd suggest this statement should be:
`if (_this->width_bits >= 0)`
However this does mean that to configure memory with infinite bandwidth the value -1 should be used instead of 0.

**Comment by haugoug** [comment]
Thanks a lot for your report ! I've merged the fix your propose.
